// Code generated by go-swagger; DO NOT EDIT.

package crypto

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCreateVaultParams creates a new CreateVaultParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateVaultParams() *CreateVaultParams {
	return &CreateVaultParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateVaultParamsWithTimeout creates a new CreateVaultParams object
// with the ability to set a timeout on a request.
func NewCreateVaultParamsWithTimeout(timeout time.Duration) *CreateVaultParams {
	return &CreateVaultParams{
		timeout: timeout,
	}
}

// NewCreateVaultParamsWithContext creates a new CreateVaultParams object
// with the ability to set a context for a request.
func NewCreateVaultParamsWithContext(ctx context.Context) *CreateVaultParams {
	return &CreateVaultParams{
		Context: ctx,
	}
}

// NewCreateVaultParamsWithHTTPClient creates a new CreateVaultParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateVaultParamsWithHTTPClient(client *http.Client) *CreateVaultParams {
	return &CreateVaultParams{
		HTTPClient: client,
	}
}

/* CreateVaultParams contains all the parameters to send to the API endpoint
   for the create vault operation.

   Typically these are written to a http.Request.
*/
type CreateVaultParams struct {

	/* Data.

	   Vault data
	*/
	Data map[string]string

	/* Name.

	   Vault name
	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create vault params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateVaultParams) WithDefaults() *CreateVaultParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create vault params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateVaultParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create vault params
func (o *CreateVaultParams) WithTimeout(timeout time.Duration) *CreateVaultParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create vault params
func (o *CreateVaultParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create vault params
func (o *CreateVaultParams) WithContext(ctx context.Context) *CreateVaultParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create vault params
func (o *CreateVaultParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create vault params
func (o *CreateVaultParams) WithHTTPClient(client *http.Client) *CreateVaultParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create vault params
func (o *CreateVaultParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the create vault params
func (o *CreateVaultParams) WithData(data map[string]string) *CreateVaultParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the create vault params
func (o *CreateVaultParams) SetData(data map[string]string) {
	o.Data = data
}

// WithName adds the name to the create vault params
func (o *CreateVaultParams) WithName(name string) *CreateVaultParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the create vault params
func (o *CreateVaultParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *CreateVaultParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
