// Code generated by go-swagger; DO NOT EDIT.

package crypto

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/flexlet/flexagent-client-go/models"
)

// NewDecryptParams creates a new DecryptParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDecryptParams() *DecryptParams {
	return &DecryptParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDecryptParamsWithTimeout creates a new DecryptParams object
// with the ability to set a timeout on a request.
func NewDecryptParamsWithTimeout(timeout time.Duration) *DecryptParams {
	return &DecryptParams{
		timeout: timeout,
	}
}

// NewDecryptParamsWithContext creates a new DecryptParams object
// with the ability to set a context for a request.
func NewDecryptParamsWithContext(ctx context.Context) *DecryptParams {
	return &DecryptParams{
		Context: ctx,
	}
}

// NewDecryptParamsWithHTTPClient creates a new DecryptParams object
// with the ability to set a custom HTTPClient for a request.
func NewDecryptParamsWithHTTPClient(client *http.Client) *DecryptParams {
	return &DecryptParams{
		HTTPClient: client,
	}
}

/* DecryptParams contains all the parameters to send to the API endpoint
   for the decrypt operation.

   Typically these are written to a http.Request.
*/
type DecryptParams struct {

	/* Data.

	   Data to decrypt
	*/
	Data *models.CryptoData

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the decrypt params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DecryptParams) WithDefaults() *DecryptParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the decrypt params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DecryptParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the decrypt params
func (o *DecryptParams) WithTimeout(timeout time.Duration) *DecryptParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the decrypt params
func (o *DecryptParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the decrypt params
func (o *DecryptParams) WithContext(ctx context.Context) *DecryptParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the decrypt params
func (o *DecryptParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the decrypt params
func (o *DecryptParams) WithHTTPClient(client *http.Client) *DecryptParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the decrypt params
func (o *DecryptParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the decrypt params
func (o *DecryptParams) WithData(data *models.CryptoData) *DecryptParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the decrypt params
func (o *DecryptParams) SetData(data *models.CryptoData) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *DecryptParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
