// Code generated by go-swagger; DO NOT EDIT.

package crypto

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListVaultsParams creates a new ListVaultsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListVaultsParams() *ListVaultsParams {
	return &ListVaultsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListVaultsParamsWithTimeout creates a new ListVaultsParams object
// with the ability to set a timeout on a request.
func NewListVaultsParamsWithTimeout(timeout time.Duration) *ListVaultsParams {
	return &ListVaultsParams{
		timeout: timeout,
	}
}

// NewListVaultsParamsWithContext creates a new ListVaultsParams object
// with the ability to set a context for a request.
func NewListVaultsParamsWithContext(ctx context.Context) *ListVaultsParams {
	return &ListVaultsParams{
		Context: ctx,
	}
}

// NewListVaultsParamsWithHTTPClient creates a new ListVaultsParams object
// with the ability to set a custom HTTPClient for a request.
func NewListVaultsParamsWithHTTPClient(client *http.Client) *ListVaultsParams {
	return &ListVaultsParams{
		HTTPClient: client,
	}
}

/* ListVaultsParams contains all the parameters to send to the API endpoint
   for the list vaults operation.

   Typically these are written to a http.Request.
*/
type ListVaultsParams struct {

	/* Name.

	   Name filter
	*/
	Name *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list vaults params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListVaultsParams) WithDefaults() *ListVaultsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list vaults params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListVaultsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list vaults params
func (o *ListVaultsParams) WithTimeout(timeout time.Duration) *ListVaultsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list vaults params
func (o *ListVaultsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list vaults params
func (o *ListVaultsParams) WithContext(ctx context.Context) *ListVaultsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list vaults params
func (o *ListVaultsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list vaults params
func (o *ListVaultsParams) WithHTTPClient(client *http.Client) *ListVaultsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list vaults params
func (o *ListVaultsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the list vaults params
func (o *ListVaultsParams) WithName(name *string) *ListVaultsParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the list vaults params
func (o *ListVaultsParams) SetName(name *string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *ListVaultsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Name != nil {

		// query param name
		var qrName string

		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {

			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
