// Code generated by go-swagger; DO NOT EDIT.

package crypto

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/flexlet/flexagent-client-go/models"
)

// NewSecretDecryptParams creates a new SecretDecryptParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSecretDecryptParams() *SecretDecryptParams {
	return &SecretDecryptParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSecretDecryptParamsWithTimeout creates a new SecretDecryptParams object
// with the ability to set a timeout on a request.
func NewSecretDecryptParamsWithTimeout(timeout time.Duration) *SecretDecryptParams {
	return &SecretDecryptParams{
		timeout: timeout,
	}
}

// NewSecretDecryptParamsWithContext creates a new SecretDecryptParams object
// with the ability to set a context for a request.
func NewSecretDecryptParamsWithContext(ctx context.Context) *SecretDecryptParams {
	return &SecretDecryptParams{
		Context: ctx,
	}
}

// NewSecretDecryptParamsWithHTTPClient creates a new SecretDecryptParams object
// with the ability to set a custom HTTPClient for a request.
func NewSecretDecryptParamsWithHTTPClient(client *http.Client) *SecretDecryptParams {
	return &SecretDecryptParams{
		HTTPClient: client,
	}
}

/* SecretDecryptParams contains all the parameters to send to the API endpoint
   for the secret decrypt operation.

   Typically these are written to a http.Request.
*/
type SecretDecryptParams struct {

	/* Secret.

	   Secret to decrypt
	*/
	Secret *models.KubeSecret

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the secret decrypt params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SecretDecryptParams) WithDefaults() *SecretDecryptParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the secret decrypt params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SecretDecryptParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the secret decrypt params
func (o *SecretDecryptParams) WithTimeout(timeout time.Duration) *SecretDecryptParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the secret decrypt params
func (o *SecretDecryptParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the secret decrypt params
func (o *SecretDecryptParams) WithContext(ctx context.Context) *SecretDecryptParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the secret decrypt params
func (o *SecretDecryptParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the secret decrypt params
func (o *SecretDecryptParams) WithHTTPClient(client *http.Client) *SecretDecryptParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the secret decrypt params
func (o *SecretDecryptParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSecret adds the secret to the secret decrypt params
func (o *SecretDecryptParams) WithSecret(secret *models.KubeSecret) *SecretDecryptParams {
	o.SetSecret(secret)
	return o
}

// SetSecret adds the secret to the secret decrypt params
func (o *SecretDecryptParams) SetSecret(secret *models.KubeSecret) {
	o.Secret = secret
}

// WriteToRequest writes these params to a swagger request
func (o *SecretDecryptParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Secret != nil {
		if err := r.SetBodyParam(o.Secret); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
