// Code generated by go-swagger; DO NOT EDIT.

package crypto

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUpdateVaultParams creates a new UpdateVaultParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateVaultParams() *UpdateVaultParams {
	return &UpdateVaultParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateVaultParamsWithTimeout creates a new UpdateVaultParams object
// with the ability to set a timeout on a request.
func NewUpdateVaultParamsWithTimeout(timeout time.Duration) *UpdateVaultParams {
	return &UpdateVaultParams{
		timeout: timeout,
	}
}

// NewUpdateVaultParamsWithContext creates a new UpdateVaultParams object
// with the ability to set a context for a request.
func NewUpdateVaultParamsWithContext(ctx context.Context) *UpdateVaultParams {
	return &UpdateVaultParams{
		Context: ctx,
	}
}

// NewUpdateVaultParamsWithHTTPClient creates a new UpdateVaultParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateVaultParamsWithHTTPClient(client *http.Client) *UpdateVaultParams {
	return &UpdateVaultParams{
		HTTPClient: client,
	}
}

/* UpdateVaultParams contains all the parameters to send to the API endpoint
   for the update vault operation.

   Typically these are written to a http.Request.
*/
type UpdateVaultParams struct {

	/* Data.

	   Vault data
	*/
	Data map[string]string

	/* Name.

	   Vault name
	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update vault params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateVaultParams) WithDefaults() *UpdateVaultParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update vault params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateVaultParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update vault params
func (o *UpdateVaultParams) WithTimeout(timeout time.Duration) *UpdateVaultParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update vault params
func (o *UpdateVaultParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update vault params
func (o *UpdateVaultParams) WithContext(ctx context.Context) *UpdateVaultParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update vault params
func (o *UpdateVaultParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update vault params
func (o *UpdateVaultParams) WithHTTPClient(client *http.Client) *UpdateVaultParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update vault params
func (o *UpdateVaultParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the update vault params
func (o *UpdateVaultParams) WithData(data map[string]string) *UpdateVaultParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the update vault params
func (o *UpdateVaultParams) SetData(data map[string]string) {
	o.Data = data
}

// WithName adds the name to the update vault params
func (o *UpdateVaultParams) WithName(name string) *UpdateVaultParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the update vault params
func (o *UpdateVaultParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateVaultParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
