// Code generated by go-swagger; DO NOT EDIT.

package cronjob

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListCronJobsParams creates a new ListCronJobsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListCronJobsParams() *ListCronJobsParams {
	return &ListCronJobsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListCronJobsParamsWithTimeout creates a new ListCronJobsParams object
// with the ability to set a timeout on a request.
func NewListCronJobsParamsWithTimeout(timeout time.Duration) *ListCronJobsParams {
	return &ListCronJobsParams{
		timeout: timeout,
	}
}

// NewListCronJobsParamsWithContext creates a new ListCronJobsParams object
// with the ability to set a context for a request.
func NewListCronJobsParamsWithContext(ctx context.Context) *ListCronJobsParams {
	return &ListCronJobsParams{
		Context: ctx,
	}
}

// NewListCronJobsParamsWithHTTPClient creates a new ListCronJobsParams object
// with the ability to set a custom HTTPClient for a request.
func NewListCronJobsParamsWithHTTPClient(client *http.Client) *ListCronJobsParams {
	return &ListCronJobsParams{
		HTTPClient: client,
	}
}

/* ListCronJobsParams contains all the parameters to send to the API endpoint
   for the list cron jobs operation.

   Typically these are written to a http.Request.
*/
type ListCronJobsParams struct {

	/* Name.

	   Name filter
	*/
	Name *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list cron jobs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListCronJobsParams) WithDefaults() *ListCronJobsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list cron jobs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListCronJobsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list cron jobs params
func (o *ListCronJobsParams) WithTimeout(timeout time.Duration) *ListCronJobsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list cron jobs params
func (o *ListCronJobsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list cron jobs params
func (o *ListCronJobsParams) WithContext(ctx context.Context) *ListCronJobsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list cron jobs params
func (o *ListCronJobsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list cron jobs params
func (o *ListCronJobsParams) WithHTTPClient(client *http.Client) *ListCronJobsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list cron jobs params
func (o *ListCronJobsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the list cron jobs params
func (o *ListCronJobsParams) WithName(name *string) *ListCronJobsParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the list cron jobs params
func (o *ListCronJobsParams) SetName(name *string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *ListCronJobsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Name != nil {

		// query param name
		var qrName string

		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {

			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
