// Code generated by go-swagger; DO NOT EDIT.

package cronjob

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewQueryCronJobParams creates a new QueryCronJobParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewQueryCronJobParams() *QueryCronJobParams {
	return &QueryCronJobParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewQueryCronJobParamsWithTimeout creates a new QueryCronJobParams object
// with the ability to set a timeout on a request.
func NewQueryCronJobParamsWithTimeout(timeout time.Duration) *QueryCronJobParams {
	return &QueryCronJobParams{
		timeout: timeout,
	}
}

// NewQueryCronJobParamsWithContext creates a new QueryCronJobParams object
// with the ability to set a context for a request.
func NewQueryCronJobParamsWithContext(ctx context.Context) *QueryCronJobParams {
	return &QueryCronJobParams{
		Context: ctx,
	}
}

// NewQueryCronJobParamsWithHTTPClient creates a new QueryCronJobParams object
// with the ability to set a custom HTTPClient for a request.
func NewQueryCronJobParamsWithHTTPClient(client *http.Client) *QueryCronJobParams {
	return &QueryCronJobParams{
		HTTPClient: client,
	}
}

/* QueryCronJobParams contains all the parameters to send to the API endpoint
   for the query cron job operation.

   Typically these are written to a http.Request.
*/
type QueryCronJobParams struct {

	/* ID.

	   Cronjob id
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the query cron job params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QueryCronJobParams) WithDefaults() *QueryCronJobParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the query cron job params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QueryCronJobParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the query cron job params
func (o *QueryCronJobParams) WithTimeout(timeout time.Duration) *QueryCronJobParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the query cron job params
func (o *QueryCronJobParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the query cron job params
func (o *QueryCronJobParams) WithContext(ctx context.Context) *QueryCronJobParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the query cron job params
func (o *QueryCronJobParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the query cron job params
func (o *QueryCronJobParams) WithHTTPClient(client *http.Client) *QueryCronJobParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the query cron job params
func (o *QueryCronJobParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the query cron job params
func (o *QueryCronJobParams) WithID(id string) *QueryCronJobParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the query cron job params
func (o *QueryCronJobParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *QueryCronJobParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
