// Code generated by go-swagger; DO NOT EDIT.

package cronjob

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewStartCronJobParams creates a new StartCronJobParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewStartCronJobParams() *StartCronJobParams {
	return &StartCronJobParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewStartCronJobParamsWithTimeout creates a new StartCronJobParams object
// with the ability to set a timeout on a request.
func NewStartCronJobParamsWithTimeout(timeout time.Duration) *StartCronJobParams {
	return &StartCronJobParams{
		timeout: timeout,
	}
}

// NewStartCronJobParamsWithContext creates a new StartCronJobParams object
// with the ability to set a context for a request.
func NewStartCronJobParamsWithContext(ctx context.Context) *StartCronJobParams {
	return &StartCronJobParams{
		Context: ctx,
	}
}

// NewStartCronJobParamsWithHTTPClient creates a new StartCronJobParams object
// with the ability to set a custom HTTPClient for a request.
func NewStartCronJobParamsWithHTTPClient(client *http.Client) *StartCronJobParams {
	return &StartCronJobParams{
		HTTPClient: client,
	}
}

/* StartCronJobParams contains all the parameters to send to the API endpoint
   for the start cron job operation.

   Typically these are written to a http.Request.
*/
type StartCronJobParams struct {

	/* ID.

	   Cronjob id
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the start cron job params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StartCronJobParams) WithDefaults() *StartCronJobParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the start cron job params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StartCronJobParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the start cron job params
func (o *StartCronJobParams) WithTimeout(timeout time.Duration) *StartCronJobParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the start cron job params
func (o *StartCronJobParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the start cron job params
func (o *StartCronJobParams) WithContext(ctx context.Context) *StartCronJobParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the start cron job params
func (o *StartCronJobParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the start cron job params
func (o *StartCronJobParams) WithHTTPClient(client *http.Client) *StartCronJobParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the start cron job params
func (o *StartCronJobParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the start cron job params
func (o *StartCronJobParams) WithID(id string) *StartCronJobParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the start cron job params
func (o *StartCronJobParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *StartCronJobParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
