// Code generated by go-swagger; DO NOT EDIT.

package cronjob

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/flexlet/flexagent-client-go/models"
)

// NewSubmitCronJobsParams creates a new SubmitCronJobsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSubmitCronJobsParams() *SubmitCronJobsParams {
	return &SubmitCronJobsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSubmitCronJobsParamsWithTimeout creates a new SubmitCronJobsParams object
// with the ability to set a timeout on a request.
func NewSubmitCronJobsParamsWithTimeout(timeout time.Duration) *SubmitCronJobsParams {
	return &SubmitCronJobsParams{
		timeout: timeout,
	}
}

// NewSubmitCronJobsParamsWithContext creates a new SubmitCronJobsParams object
// with the ability to set a context for a request.
func NewSubmitCronJobsParamsWithContext(ctx context.Context) *SubmitCronJobsParams {
	return &SubmitCronJobsParams{
		Context: ctx,
	}
}

// NewSubmitCronJobsParamsWithHTTPClient creates a new SubmitCronJobsParams object
// with the ability to set a custom HTTPClient for a request.
func NewSubmitCronJobsParamsWithHTTPClient(client *http.Client) *SubmitCronJobsParams {
	return &SubmitCronJobsParams{
		HTTPClient: client,
	}
}

/* SubmitCronJobsParams contains all the parameters to send to the API endpoint
   for the submit cron jobs operation.

   Typically these are written to a http.Request.
*/
type SubmitCronJobsParams struct {

	/* Spec.

	   Cronjobs spec
	*/
	Spec []*models.CronJobSpec

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the submit cron jobs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SubmitCronJobsParams) WithDefaults() *SubmitCronJobsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the submit cron jobs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SubmitCronJobsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the submit cron jobs params
func (o *SubmitCronJobsParams) WithTimeout(timeout time.Duration) *SubmitCronJobsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the submit cron jobs params
func (o *SubmitCronJobsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the submit cron jobs params
func (o *SubmitCronJobsParams) WithContext(ctx context.Context) *SubmitCronJobsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the submit cron jobs params
func (o *SubmitCronJobsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the submit cron jobs params
func (o *SubmitCronJobsParams) WithHTTPClient(client *http.Client) *SubmitCronJobsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the submit cron jobs params
func (o *SubmitCronJobsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSpec adds the spec to the submit cron jobs params
func (o *SubmitCronJobsParams) WithSpec(spec []*models.CronJobSpec) *SubmitCronJobsParams {
	o.SetSpec(spec)
	return o
}

// SetSpec adds the spec to the submit cron jobs params
func (o *SubmitCronJobsParams) SetSpec(spec []*models.CronJobSpec) {
	o.Spec = spec
}

// WriteToRequest writes these params to a swagger request
func (o *SubmitCronJobsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Spec != nil {
		if err := r.SetBodyParam(o.Spec); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
