// Code generated by go-swagger; DO NOT EDIT.

package cronjob

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/flexlet/flexagent-client-go/models"
)

// NewUpdateCronJobParams creates a new UpdateCronJobParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateCronJobParams() *UpdateCronJobParams {
	return &UpdateCronJobParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateCronJobParamsWithTimeout creates a new UpdateCronJobParams object
// with the ability to set a timeout on a request.
func NewUpdateCronJobParamsWithTimeout(timeout time.Duration) *UpdateCronJobParams {
	return &UpdateCronJobParams{
		timeout: timeout,
	}
}

// NewUpdateCronJobParamsWithContext creates a new UpdateCronJobParams object
// with the ability to set a context for a request.
func NewUpdateCronJobParamsWithContext(ctx context.Context) *UpdateCronJobParams {
	return &UpdateCronJobParams{
		Context: ctx,
	}
}

// NewUpdateCronJobParamsWithHTTPClient creates a new UpdateCronJobParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateCronJobParamsWithHTTPClient(client *http.Client) *UpdateCronJobParams {
	return &UpdateCronJobParams{
		HTTPClient: client,
	}
}

/* UpdateCronJobParams contains all the parameters to send to the API endpoint
   for the update cron job operation.

   Typically these are written to a http.Request.
*/
type UpdateCronJobParams struct {

	/* ID.

	   Cronjob id
	*/
	ID string

	/* Spec.

	   Cronjob spec
	*/
	Spec *models.CronJobSpec

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update cron job params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateCronJobParams) WithDefaults() *UpdateCronJobParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update cron job params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateCronJobParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update cron job params
func (o *UpdateCronJobParams) WithTimeout(timeout time.Duration) *UpdateCronJobParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update cron job params
func (o *UpdateCronJobParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update cron job params
func (o *UpdateCronJobParams) WithContext(ctx context.Context) *UpdateCronJobParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update cron job params
func (o *UpdateCronJobParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update cron job params
func (o *UpdateCronJobParams) WithHTTPClient(client *http.Client) *UpdateCronJobParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update cron job params
func (o *UpdateCronJobParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the update cron job params
func (o *UpdateCronJobParams) WithID(id string) *UpdateCronJobParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update cron job params
func (o *UpdateCronJobParams) SetID(id string) {
	o.ID = id
}

// WithSpec adds the spec to the update cron job params
func (o *UpdateCronJobParams) WithSpec(spec *models.CronJobSpec) *UpdateCronJobParams {
	o.SetSpec(spec)
	return o
}

// SetSpec adds the spec to the update cron job params
func (o *UpdateCronJobParams) SetSpec(spec *models.CronJobSpec) {
	o.Spec = spec
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateCronJobParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}
	if o.Spec != nil {
		if err := r.SetBodyParam(o.Spec); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
