// Code generated by go-swagger; DO NOT EDIT.

package job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/flexlet/flexagent-client-go/models"
)

// NewInputParams creates a new InputParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewInputParams() *InputParams {
	return &InputParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewInputParamsWithTimeout creates a new InputParams object
// with the ability to set a timeout on a request.
func NewInputParamsWithTimeout(timeout time.Duration) *InputParams {
	return &InputParams{
		timeout: timeout,
	}
}

// NewInputParamsWithContext creates a new InputParams object
// with the ability to set a context for a request.
func NewInputParamsWithContext(ctx context.Context) *InputParams {
	return &InputParams{
		Context: ctx,
	}
}

// NewInputParamsWithHTTPClient creates a new InputParams object
// with the ability to set a custom HTTPClient for a request.
func NewInputParamsWithHTTPClient(client *http.Client) *InputParams {
	return &InputParams{
		HTTPClient: client,
	}
}

/* InputParams contains all the parameters to send to the API endpoint
   for the input operation.

   Typically these are written to a http.Request.
*/
type InputParams struct {

	/* Input.

	   Input data
	*/
	Input *models.JobInput

	/* Urn.

	   Job urn
	*/
	Urn string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the input params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *InputParams) WithDefaults() *InputParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the input params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *InputParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the input params
func (o *InputParams) WithTimeout(timeout time.Duration) *InputParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the input params
func (o *InputParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the input params
func (o *InputParams) WithContext(ctx context.Context) *InputParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the input params
func (o *InputParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the input params
func (o *InputParams) WithHTTPClient(client *http.Client) *InputParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the input params
func (o *InputParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInput adds the input to the input params
func (o *InputParams) WithInput(input *models.JobInput) *InputParams {
	o.SetInput(input)
	return o
}

// SetInput adds the input to the input params
func (o *InputParams) SetInput(input *models.JobInput) {
	o.Input = input
}

// WithUrn adds the urn to the input params
func (o *InputParams) WithUrn(urn string) *InputParams {
	o.SetUrn(urn)
	return o
}

// SetUrn adds the urn to the input params
func (o *InputParams) SetUrn(urn string) {
	o.Urn = urn
}

// WriteToRequest writes these params to a swagger request
func (o *InputParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Input != nil {
		if err := r.SetBodyParam(o.Input); err != nil {
			return err
		}
	}

	// path param urn
	if err := r.SetPathParam("urn", o.Urn); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
