// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// JobOutput Job output
//
// swagger:model JobOutput
type JobOutput struct {

	// Last output line
	// Required: true
	LastLine int32 `json:"lastLine"`

	// Output
	// Required: true
	Lines []string `json:"lines"`

	// There is more line
	// Required: true
	MoreLine bool `json:"moreLine"`
}

// Validate validates this job output
func (m *JobOutput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLastLine(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLines(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMoreLine(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *JobOutput) validateLastLine(formats strfmt.Registry) error {

	if err := validate.Required("lastLine", "body", int32(m.LastLine)); err != nil {
		return err
	}

	return nil
}

func (m *JobOutput) validateLines(formats strfmt.Registry) error {

	if err := validate.Required("lines", "body", m.Lines); err != nil {
		return err
	}

	return nil
}

func (m *JobOutput) validateMoreLine(formats strfmt.Registry) error {

	if err := validate.Required("moreLine", "body", bool(m.MoreLine)); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this job output based on context it is used
func (m *JobOutput) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *JobOutput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *JobOutput) UnmarshalBinary(b []byte) error {
	var res JobOutput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
