// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// JobInput Job input
//
// swagger:model JobInput
type JobInput struct {

	// Input data
	// Required: true
	Data string `json:"data"`

	// Expect string
	Expect *string `json:"expect,omitempty"`

	// Expect timeout in seconds
	Timeout *int32 `json:"timeout,omitempty"`
}

// Validate validates this job input
func (m *JobInput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *JobInput) validateData(formats strfmt.Registry) error {

	if err := validate.RequiredString("data", "body", m.Data); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this job input based on context it is used
func (m *JobInput) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *JobInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *JobInput) UnmarshalBinary(b []byte) error {
	var res JobInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
