// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// KubeMetadata K8S metadata
//
// swagger:model KubeMetadata
type KubeMetadata struct {

	// Annotations
	Annotations map[string]string `json:"annotations,omitempty"`

	// Labels
	Labels map[string]string `json:"labels,omitempty"`

	// Name
	// Required: true
	Name string `json:"name"`

	// Name
	Namespace *string `json:"namespace,omitempty"`
}

// Validate validates this kube metadata
func (m *KubeMetadata) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *KubeMetadata) validateName(formats strfmt.Registry) error {

	if err := validate.RequiredString("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this kube metadata based on context it is used
func (m *KubeMetadata) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *KubeMetadata) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *KubeMetadata) UnmarshalBinary(b []byte) error {
	var res KubeMetadata
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
